// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/aliskhannn/calendar-service/internal/model"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockeventRepo is a mock of eventRepo interface.
type MockeventRepo struct {
	ctrl     *gomock.Controller
	recorder *MockeventRepoMockRecorder
}

// MockeventRepoMockRecorder is the mock recorder for MockeventRepo.
type MockeventRepoMockRecorder struct {
	mock *MockeventRepo
}

// NewMockeventRepo creates a new mock instance.
func NewMockeventRepo(ctrl *gomock.Controller) *MockeventRepo {
	mock := &MockeventRepo{ctrl: ctrl}
	mock.recorder = &MockeventRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockeventRepo) EXPECT() *MockeventRepoMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockeventRepo) CreateEvent(ctx context.Context, event model.Event) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, event)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockeventRepoMockRecorder) CreateEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockeventRepo)(nil).CreateEvent), ctx, event)
}

// DeleteEvent mocks base method.
func (m *MockeventRepo) DeleteEvent(ctx context.Context, eventID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvent", ctx, eventID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEvent indicates an expected call of DeleteEvent.
func (mr *MockeventRepoMockRecorder) DeleteEvent(ctx, eventID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvent", reflect.TypeOf((*MockeventRepo)(nil).DeleteEvent), ctx, eventID, userID)
}

// GetEventsForDay mocks base method.
func (m *MockeventRepo) GetEventsForDay(ctx context.Context, userID uuid.UUID, date time.Time) ([]model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsForDay", ctx, userID, date)
	ret0, _ := ret[0].([]model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsForDay indicates an expected call of GetEventsForDay.
func (mr *MockeventRepoMockRecorder) GetEventsForDay(ctx, userID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsForDay", reflect.TypeOf((*MockeventRepo)(nil).GetEventsForDay), ctx, userID, date)
}

// GetEventsForMonth mocks base method.
func (m *MockeventRepo) GetEventsForMonth(ctx context.Context, userID uuid.UUID, date time.Time) ([]model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsForMonth", ctx, userID, date)
	ret0, _ := ret[0].([]model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsForMonth indicates an expected call of GetEventsForMonth.
func (mr *MockeventRepoMockRecorder) GetEventsForMonth(ctx, userID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsForMonth", reflect.TypeOf((*MockeventRepo)(nil).GetEventsForMonth), ctx, userID, date)
}

// GetEventsForWeek mocks base method.
func (m *MockeventRepo) GetEventsForWeek(ctx context.Context, userID uuid.UUID, date time.Time) ([]model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsForWeek", ctx, userID, date)
	ret0, _ := ret[0].([]model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsForWeek indicates an expected call of GetEventsForWeek.
func (mr *MockeventRepoMockRecorder) GetEventsForWeek(ctx, userID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsForWeek", reflect.TypeOf((*MockeventRepo)(nil).GetEventsForWeek), ctx, userID, date)
}

// UpdateEvent mocks base method.
func (m *MockeventRepo) UpdateEvent(ctx context.Context, event model.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEvent indicates an expected call of UpdateEvent.
func (mr *MockeventRepoMockRecorder) UpdateEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvent", reflect.TypeOf((*MockeventRepo)(nil).UpdateEvent), ctx, event)
}
